force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event</relationshipLabel>
    <relationshipName>Event</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventSpeakerHandler.cls
public with sharing class EventSpeakerHandler {
    
    // Bu metot Trigger'dan gelen listeyi alır ve kontrol eder
    public static void checkDuplicates(List<Event_Speaker__c> newRecords) {
        
        Set<Id> speakerIds = new Set<Id>();
        Set<Id> eventIds = new Set<Id>();

        // 1. Gelen kayıtlardaki ID'leri topla
        for (Event_Speaker__c es : newRecords) {
            if (es.Speaker__c != null && es.Event__c != null) {
                speakerIds.add(es.Speaker__c);
                eventIds.add(es.Event__c);
            }
        }

        // 2. Veritabanında mevcut kayıt var mı sorgula (SOQL)
        List<Event_Speaker__c> existingRecords = [SELECT Speaker__c, Event__c 
                                                  FROM Event_Speaker__c 
                                                  WHERE Speaker__c IN :speakerIds 
                                                  AND Event__c IN :eventIds];

        // 3. Karşılaştır ve hata varsa işaretle
        for (Event_Speaker__c newRec : newRecords) {
            for (Event_Speaker__c oldRec : existingRecords) {
                if (newRec.Speaker__c == oldRec.Speaker__c && newRec.Event__c == oldRec.Event__c) {
                    newRec.addError('Dikkat! Bu konuşmacı bu etkinliğe zaten eklenmiş.');
                }
            }
        }
    }
}